### ISSUE TITLE
Make List of GUI Information

### ISSUE THREAD

**Issue by 19aanand** [sbroboticsteam/robocup-rescue-23#3]
We will be making a list of information that needs to be displayed on the controller application! The link to the document will be posted soon.

@notALiee You will be working on determining what drivetrain information is necessary to display (ie. speed, flipper information, etc.)

@kennyproc @SummerWang00 You will be working on determining what arm information is necessary to to display on the controller (ie. angles of each joint, gripper position, etc.) Please make sure to communicate with Victoria Joseph (the Arm subsystem lead) to understand the specifics of the design.

**Comment by 19aanand** [comment]
[GUI Information Document](https://docs.google.com/document/d/1lc11GR3LKiBjIf5b1x1Vnm2vErA2JayN8mZ52-OmQLc/edit)

**Comment by notALiee** [comment]
I added the drivetrain information to the document. But I'm unsure if that is all the information needed.

**Comment by 19aanand** [comment]
Natalie, I left some comments on the document. Great first pass!

**Comment by 19aanand** [comment]
Closing issue since GUI information has been compiled.
